version: "3.8"
services:
  elastic-search:
    container_name: elasticSearch
    image: library/elasticsearch:7.14.0
    ports:
      - "9200:9200"
    environment:
      discovery.type: single-node
    networks:
      - spring-watching
    restart: unless-stopped

  kibana:
    container_name: kibana
    image: library/kibana:6.8.18
    ports:
      - "5601:5601"
    networks:
      - spring-watching
    depends_on:
      - elastic-search
    restart: unless-stopped

  metricbeat:
    container_name: metricbeat
    image: docker.elastic.co/beats/metricbeat:7.4.2
    volumes:
      - ./metric-beat/metricbeat/metricbeat.yml:/usr/share/metricbeat/metricbeat.yml
    user: root
    depends_on:
      - elastic-search
      - metrics
    networks:
      - spring-watching

  metrics:
    container_name: metrics
    build: 
      context: services/metrics
      dockerfile: ../services/metrics/Dockerfile
    ports:
      - 2001:2001
    networks:
      - spring-watching

networks:
  spring-watching:
    driver: bridge

