global:
  scrape_interval: 5s
  evaluation_interval: 5s
rule_files:
    - /etc/prometheus/prometheus.rules
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['127.0.0.1:9090']
  - job_name: 'docker'
    static_configs:
      - targets: ['docker.for.mac.host.internal:9323']
  - job_name: 'metrics-client'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['metrics-client:2001']
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['user-service:2002']
